[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning
    ignore:urllib3 v2 only supports OpenSSL 1\.1\.1\+.*:Warning
    ignore:The 'app' shortcut is now deprecated\. Use the explicit style 'transport=WSGITransport\(app=...\)' instead\.:DeprecationWarning
