package com.fitgpt.app.data.model

/**
 * Suggested wardrobe metadata generated by backend heuristics.
 */
data class TagSuggestion(
    val generated: Boolean,
    val suggestedClothingType: String?,
    val suggestedFitTag: String?,
    val suggestedColors: List<String>,
    val suggestedSeasonTags: List<String>,
    val suggestedStyleTags: List<String>,
    val suggestedOccasionTags: List<String>
)
